# Project information
site_name: Microbial Ecology Group
site_url: https://meglab.org/
site_author: Microbial Ecology Group
site_description: Research addressing the issues of microbial ecology in animal, public, and environmental health.

# Copyright
copyright: '&copy; Copyright Microbial Ecology Group.'

# Footer mod: https://squidfunk.github.io/mkdocs-material/setup/setting-up-the-footer/#generator-notice 
extra:
  generator: false

# Configuration
theme:
  name: material
  custom_dir: overrides
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:  # from .icons path. Add to theme override for custom logo.
    logo: meglab-logo  # top left header logo
  favicon: assets/meglab-logo.png #browser tab logo

# Custom theme additions
extra_css:
  - stylesheets/extra.css

# Custom javascript
extra_javascript:
  - javascripts/extra.js

# Extensions
markdown_extensions:
  - tables
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page Tree
nav:
  - Home: index.md
  - MEGARes : 
    - Home: megares/index.md
    - Download: megares/download.md
  - AMR++ Pipeline :
    - Home: amrplusplus/index.md
    - Getting Started: amrplusplus/latest/gettingstarted.md    
    - Installation: amrplusplus/latest/installation.md
    - Usage: amrplusplus/latest/usage.md
    - Configuration: amrplusplus/latest/configuration.md
    - Output: amrplusplus/latest/output.md  
    - Dependencies: amrplusplus/latest/dependencies.md
    - Software Requirements: amrplusplus/latest/requirements.md
    - FAQ: amrplusplus/latest/FAQs.md
    - Citing AMR++: amrplusplus/latest/citing.md    
    - Contact: amrplusplus/latest/contact.md
    - References: amrplusplus/latest/references.md    
    - AMR++ v2.0:
      - Introduction: amrplusplus/v2/introduction.md      
      - Accessing AMR Plus Plus v2.0: amrplusplus/v2/accessing_AMR.md
      - Installation: amrplusplus/v2/installation.md
      - Usage: amrplusplus/v2/usage.md
      - Configuration: amrplusplus/v2/configuration.md
      - Output: amrplusplus/v2/output.md  
      - Dependencies: amrplusplus/v2/dependencies.md
      - Software Requirements: amrplusplus/v2/requirements.md
      - FAQ: amrplusplus/v2/FAQs.md
      - Citing AMR++: amrplusplus/v2/citing.md      
      - Contact: amrplusplus/v2/contact.md
      - References: amrplusplus/v2/references.md      
    - AMR++ v1.1:
      - Introduction: amrplusplus/v1/introduction.md
      - Example Analysis and Output: amrplusplus/v1/analysisoutput.md
      - Initial Setup:
        - Installation to Run AMR++: amrplusplus/v1/setup/installation.md
        - Import AMR++ Workflow: amrplusplus/v1/setup/import.md
      - Running AMR++:
        - Upload Data into AMR++: amrplusplus/v1/running/upload.md
        - Run AMR++ Workflow: amrplusplus/v1/running/runworkflow.md
      - AMR++ Documentation:
        - Pipeline Description: amrplusplus/v1/documentation/pipeline.md
        - User Manual (Options and Settings): amrplusplus/v1/documentation/usermanual.md
        - Docker Commands: amrplusplus/v1/documentation/docker.md
      - References: amrplusplus/v1/references.md
      - Citing AMR++: amrplusplus/v1/citing.md
      - Contact: amrplusplus/v1/contact.md  
